includes:
- configs/mex-0.25/equiformer_v2/base_ebm.yml
- configs/mex-0.25/params/base_param.yml
dataset:
  train:
    format: lmdb
    src: data/extrapolation_benchmark/mp_gvrh_large/train
    weighted_sample: false
    train_max_y: 1.7781512503836436
    train_min_y: 0.0
    transforms:
      normalizer:
        y:
          mean: 1.3844942412528263
          stdev: 0.30268260885881876
  val:
    src: data/extrapolation_benchmark/mp_gvrh_large/val
  test:
    src: data/extrapolation_benchmark/mp_gvrh_large/test
logger: tensorboard
