includes:
- configs/erm/equiformer_v2/base.yml
- configs/erm/params/base_param.yml
dataset:
  train:
    src: data/extrapolation_benchmark/mp_gvrh_small/train
    weighted_sample: false
    full_max_y: 2.718501688867274
    full_min_y: 0.0
    transforms:
      normalizer:
        y:
          mean: 1.7434881930988457
          stdev: 0.2196231027207981
  val:
    src: data/extrapolation_benchmark/mp_gvrh_small/val
  test:
    src: data/extrapolation_benchmark/mp_gvrh_small/test
logger: tensorboard
