includes:
- configs/erm/equiformer_v2/base.yml
- configs/erm/params/base_param.yml
dataset:
  train:
    src: data/extrapolation_benchmark/mp_phonons_small/train
    weighted_sample: false
    full_max_y: 8.200766848958235
    full_min_y: 4.087416859737459
    transforms:
      normalizer:
        y:
          mean: 6.454379382799365
          stdev: 0.5111314228546016
  val:
    src: data/extrapolation_benchmark/mp_phonons_small/val
  test:
    src: data/extrapolation_benchmark/mp_phonons_small/test
logger: tensorboard
