optim:
  batch_size: 64
  eval_batch_size: 128
  load_balancing: atoms
  num_workers: 4
  max_epochs: 200
  ema_decay: 0.999
  clip_grad_norm: 10.0
  lr_initial: 0.0001
  optimizer: AdamW
  optimizer_params:
    weight_decay: 0.0
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
